### ISSUE TITLE
Problem of reproducing the 2D version of CAGNET

### ISSUE THREAD

**Issue by wanghemeng** [PASSIONLab/CAGNET#11]
Hi,

It's a really nice work and I have successfully reproduced the 1.5d and 3d implementation.

However, when I tried to implement the 2d version with following command:

```
MASTER_ADDR=127.0.0.1 MASTER_PORT=12345 RANK=0 WORLD_SIZE=1 python gcn_distr_2d.py --accperrank=1 --epochs=3 --graphname=Cora --timing=False --midlayer=16 --runcount 1
```

I got the following error:

```
Namespace(accperrank=1, accuracy=None, activations=None, download=None, epochs=3, graphname='Cora', local_rank=None, midlayer=16, normalization=None, runcount=1, timing='False')
Arguments: epochs: 3 graph: Cora timing: False mid: 16 norm: False act: False acc: False
device: cuda:0
devid: 0 8
Processes: 1
torch.Size([2708, 2708])
torch.Size([2708, 1433])
rank: 0 adj_matrix_loc.nnz: 10556
Starting training... rank 0 run 0
/root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):
  File "gcn_distr_2d.py", line 1575, in <module>
    print(main())
  File "gcn_distr_2d.py", line 1533, in main
    device, outputs, acc_per_rank, run)
  File "gcn_distr_2d.py", line 1394, in init_process
    acc_per_rank)
  File "gcn_distr_2d.py", line 1301, in run
    col_groups, transpose_group)
  File "gcn_distr_2d.py", line 989, in train
    loss_calc.backward()
  File "/root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "gcn_distr_2d.py", line 858, in backward
    col_groups, weight.size(0), node_count, weight.size(1))
  File "gcn_distr_2d.py", line 251, in summa
    dist.broadcast(acol, row_src_rank, row_groups[row])
  File "/root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 816, in broadcast
    work.wait()
RuntimeError: a leaf Variable that requires grad has been used in an in-place operation. (check_inplace at /tmp/pip-req-build-808afw3c/torch/csrc/autograd/VariableTypeUtils.h:46)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7467315bb2ad in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x3df773d (0x7467033f773d in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x2bc85d (0x7467222bc85d in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0xae9053 (0x746722ae9053 in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xae928c (0x746722ae928c in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: c10d::ProcessGroupGloo::runLoop(int) + 0x150 (0x746722ade280 in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xdbbf4 (0x7466fecdbbf4 in /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6)
frame #7: <unknown function> + 0x94ac3 (0x746733494ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #8: <unknown function> + 0x126a40 (0x746733526a40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

Since the nccl is not available in my environment for now and I have to use the gloo backend, I'm not sure if this is the reason for the error. It would be nice if you can give some suggestions to solve my problem.

**Comment by alokpathy** [comment]
Thanks for reaching out! I'm trying to reproduce this with gloo and I was able to reproduce it on torch 1.11, though this seems to go away on torch 2.1. Have you tried that?

**Comment by wanghemeng** [comment]
Thank @alokpathy , sorry for the late reply.
We retry to reproduce the code on torch 1.11 with cuda11.3 and it works!
Thanks for your help~
